[package]
name = "rust-csv-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "0.8.29"
polars = { version = "0.25.1", features=["describe", "lazy", "strings", "json"] }