version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    # env_file:
    #   - .env
    environment:
      - DATABASE_URL=file:/usr/src/app/sqlite/db.db?socket_timeout=10&connection_limit=1
    ports:
      - 3668:3000
    restart: always
